/**
 * Slack-style `:shortcode:` emoji. A curated map of common shortcodes to their
 * Unicode character, plus helpers to expand fully-typed codes and to power the
 * composer's autocomplete. Custom (image) emoji are intentionally out of scope.
 */

export const EMOJI: Record<string, string> = {
  // faces — smiling / positive
  smile: '😄',
  smiley: '😃',
  grin: '😁',
  laughing: '😆',
  satisfied: '😆',
  sweat_smile: '😅',
  joy: '😂',
  rofl: '🤣',
  rolling_on_the_floor_laughing: '🤣',
  slightly_smiling_face: '🙂',
  upside_down_face: '🙃',
  wink: '😉',
  blush: '😊',
  innocent: '😇',
  smiling_face_with_three_hearts: '🥰',
  heart_eyes: '😍',
  star_struck: '🤩',
  kissing_heart: '😘',
  yum: '😋',
  stuck_out_tongue: '😛',
  stuck_out_tongue_winking_eye: '😜',
  zany_face: '🤪',
  stuck_out_tongue_closed_eyes: '😝',
  money_mouth_face: '🤑',
  hugs: '🤗',
  hand_over_mouth: '🤭',
  shushing_face: '🤫',
  thinking: '🤔',
  zipper_mouth_face: '🤐',
  raised_eyebrow: '🤨',
  neutral_face: '😐',
  expressionless: '😑',
  no_mouth: '😶',
  smirk: '😏',
  unamused: '😒',
  roll_eyes: '🙄',
  grimacing: '😬',
  lying_face: '🤥',
  relieved: '😌',
  pensive: '😔',
  sleepy: '😪',
  drooling_face: '🤤',
  sleeping: '😴',
  // faces — unwell / negative
  mask: '😷',
  face_with_thermometer: '🤒',
  face_with_head_bandage: '🤕',
  nauseated_face: '🤢',
  vomiting: '🤮',
  sneezing_face: '🤧',
  hot_face: '🥵',
  cold_face: '🥶',
  woozy_face: '🥴',
  dizzy_face: '😵',
  exploding_head: '🤯',
  cowboy_hat_face: '🤠',
  partying_face: '🥳',
  sunglasses: '😎',
  nerd_face: '🤓',
  confused: '😕',
  worried: '😟',
  slightly_frowning_face: '🙁',
  frowning_face: '☹️',
  open_mouth: '😮',
  hushed: '😯',
  astonished: '😲',
  flushed: '😳',
  pleading_face: '🥺',
  frowning: '😦',
  anguished: '😧',
  fearful: '😨',
  cold_sweat: '😰',
  disappointed_relieved: '😥',
  cry: '😢',
  sob: '😭',
  scream: '😱',
  confounded: '😖',
  persevere: '😣',
  disappointed: '😞',
  sweat: '😓',
  weary: '😩',
  tired_face: '😫',
  yawning_face: '🥱',
  triumph: '😤',
  rage: '😡',
  angry: '😠',
  cursing_face: '🤬',
  smiling_imp: '😈',
  imp: '👿',
  skull: '💀',
  skull_and_crossbones: '☠️',
  poop: '💩',
  hankey: '💩',
  clown_face: '🤡',
  ghost: '👻',
  alien: '👽',
  robot: '🤖',
  jack_o_lantern: '🎃',
  // gestures / hands
  wave: '👋',
  raised_back_of_hand: '🤚',
  raised_hand: '✋',
  vulcan_salute: '🖖',
  ok_hand: '👌',
  pinching_hand: '🤏',
  v: '✌️',
  crossed_fingers: '🤞',
  love_you_gesture: '🤟',
  metal: '🤘',
  call_me_hand: '🤙',
  point_left: '👈',
  point_right: '👉',
  point_up_2: '👆',
  point_down: '👇',
  point_up: '☝️',
  thumbsup: '👍',
  '+1': '👍',
  thumbsdown: '👎',
  '-1': '👎',
  fist: '✊',
  facepunch: '👊',
  punch: '👊',
  fist_left: '🤛',
  fist_right: '🤜',
  clap: '👏',
  raised_hands: '🙌',
  open_hands: '👐',
  palms_up_together: '🤲',
  handshake: '🤝',
  pray: '🙏',
  writing_hand: '✍️',
  nail_care: '💅',
  muscle: '💪',
  // people
  eyes: '👀',
  eye: '👁️',
  brain: '🧠',
  tongue: '👅',
  ear: '👂',
  baby: '👶',
  person_shrugging: '🤷',
  shrug: '🤷',
  person_facepalming: '🤦',
  facepalm: '🤦',
  dancer: '💃',
  man_dancing: '🕺',
  walking: '🚶',
  running: '🏃',
  // hearts / symbols
  heart: '❤️',
  orange_heart: '🧡',
  yellow_heart: '💛',
  green_heart: '💚',
  blue_heart: '💙',
  purple_heart: '💜',
  black_heart: '🖤',
  white_heart: '🤍',
  brown_heart: '🤎',
  broken_heart: '💔',
  two_hearts: '💕',
  sparkling_heart: '💖',
  heartpulse: '💗',
  cupid: '💘',
  revolving_hearts: '💞',
  heartbeat: '💓',
  100: '💯',
  anger: '💢',
  boom: '💥',
  collision: '💥',
  dizzy: '💫',
  sweat_drops: '💦',
  dash: '💨',
  hole: '🕳️',
  speech_balloon: '💬',
  thought_balloon: '💭',
  zzz: '💤',
  // celebration / objects
  fire: '🔥',
  sparkles: '✨',
  star: '⭐',
  star2: '🌟',
  tada: '🎉',
  confetti_ball: '🎊',
  balloon: '🎈',
  gift: '🎁',
  trophy: '🏆',
  medal_sports: '🏅',
  first_place_medal: '🥇',
  crown: '👑',
  gem: '💎',
  rocket: '🚀',
  zap: '⚡',
  bulb: '💡',
  moneybag: '💰',
  dollar: '💵',
  bell: '🔔',
  lock: '🔒',
  key: '🔑',
  hammer: '🔨',
  wrench: '🔧',
  gear: '⚙️',
  bomb: '💣',
  warning: '⚠️',
  no_entry: '⛔',
  white_check_mark: '✅',
  heavy_check_mark: '✔️',
  ballot_box_with_check: '☑️',
  x: '❌',
  negative_squared_cross_mark: '❎',
  question: '❓',
  exclamation: '❗',
  bangbang: '‼️',
  recycle: '♻️',
  // nature / food
  dog: '🐶',
  cat: '🐱',
  mouse: '🐭',
  rabbit: '🐰',
  fox_face: '🦊',
  bear: '🐻',
  panda_face: '🐼',
  koala: '🐨',
  tiger: '🐯',
  lion: '🦁',
  cow: '🐮',
  pig: '🐷',
  frog: '🐸',
  monkey_face: '🐵',
  chicken: '🐔',
  penguin: '🐧',
  bird: '🐦',
  unicorn: '🦄',
  bee: '🐝',
  bug: '🐛',
  butterfly: '🦋',
  snail: '🐌',
  whale: '🐳',
  dolphin: '🐬',
  fish: '🐟',
  octopus: '🐙',
  turtle: '🐢',
  snake: '🐍',
  dragon: '🐉',
  cactus: '🌵',
  christmas_tree: '🎄',
  evergreen_tree: '🌲',
  palm_tree: '🌴',
  seedling: '🌱',
  herb: '🌿',
  four_leaf_clover: '🍀',
  maple_leaf: '🍁',
  mushroom: '🍄',
  bouquet: '💐',
  cherry_blossom: '🌸',
  rose: '🌹',
  sunflower: '🌻',
  hibiscus: '🌺',
  sun_with_face: '🌞',
  full_moon: '🌕',
  crescent_moon: '🌙',
  earth_americas: '🌎',
  rainbow: '🌈',
  cloud: '☁️',
  sunny: '☀️',
  snowflake: '❄️',
  snowman: '⛄',
  ocean: '🌊',
  droplet: '💧',
  coffee: '☕',
  tea: '🍵',
  beer: '🍺',
  beers: '🍻',
  clinking_glasses: '🥂',
  wine_glass: '🍷',
  cocktail: '🍸',
  tropical_drink: '🍹',
  champagne: '🍾',
  pizza: '🍕',
  hamburger: '🍔',
  fries: '🍟',
  hotdog: '🌭',
  taco: '🌮',
  burrito: '🌯',
  popcorn: '🍿',
  doughnut: '🍩',
  cookie: '🍪',
  cake: '🍰',
  birthday: '🎂',
  chocolate_bar: '🍫',
  candy: '🍬',
  lollipop: '🍭',
  ice_cream: '🍨',
  apple: '🍎',
  banana: '🍌',
  watermelon: '🍉',
  grapes: '🍇',
  strawberry: '🍓',
  peach: '🍑',
  cherries: '🍒',
  lemon: '🍋',
  avocado: '🥑',
  eggplant: '🍆',
  hot_pepper: '🌶️',
  corn: '🌽',
  bread: '🍞',
  cheese: '🧀',
  // activity / travel
  soccer: '⚽',
  basketball: '🏀',
  football: '🏈',
  baseball: '⚾',
  tennis: '🎾',
  bowling: '🎳',
  dart: '🎯',
  video_game: '🎮',
  game_die: '🎲',
  musical_note: '🎵',
  notes: '🎶',
  microphone: '🎤',
  headphones: '🎧',
  guitar: '🎸',
  art: '🎨',
  clapper: '🎬',
  camera: '📷',
  car: '🚗',
  taxi: '🚕',
  bus: '🚌',
  airplane: '✈️',
  ship: '🚢',
  anchor: '⚓',
  house: '🏠',
  // tech / misc
  computer: '💻',
  desktop_computer: '🖥️',
  keyboard: '⌨️',
  iphone: '📱',
  telephone: '☎️',
  battery: '🔋',
  electric_plug: '🔌',
  floppy_disk: '💾',
  cd: '💿',
  email: '📧',
  envelope: '✉️',
  inbox_tray: '📥',
  outbox_tray: '📤',
  package: '📦',
  memo: '📝',
  pencil2: '✏️',
  pushpin: '📌',
  paperclip: '📎',
  scissors: '✂️',
  calendar: '📅',
  clipboard: '📋',
  book: '📖',
  books: '📚',
  newspaper: '📰',
  mag: '🔍',
  hourglass: '⌛',
  alarm_clock: '⏰',
  watch: '⌚',
  // flags / arrows
  checkered_flag: '🏁',
  triangular_flag_on_post: '🚩',
  rainbow_flag: '🏳️‍🌈',
  arrow_right: '➡️',
  arrow_left: '⬅️',
  arrow_up: '⬆️',
  arrow_down: '⬇️',
  arrows_counterclockwise: '🔄',
  back: '🔙',
  soon: '🔜',
  ok: '🆗',
  new: '🆕',
  cool: '🆒',
  free: '🆓',
};

/**
 * Replace every fully-typed `:shortcode:` in `text` with its emoji. Unknown
 * codes are left untouched so a stray `:foo:` stays readable.
 */
export function replaceEmojiShortcodes(text: string): string {
  return text.replace(/:([a-z0-9_+-]+):/gi, (whole, code: string) => {
    const hit = EMOJI[code] ?? EMOJI[code.toLowerCase()];
    return hit ?? whole;
  });
}

export interface EmojiHit {
  code: string;
  char: string;
}

/**
 * Autocomplete candidates for a partial shortcode (the text after `:`), ranked
 * with prefix matches first. Returns at most `limit` results.
 */
export function searchEmoji(query: string, limit = 8): EmojiHit[] {
  const q = query.toLowerCase();
  if (q === '') return [];
  const prefix: EmojiHit[] = [];
  const contains: EmojiHit[] = [];
  for (const code of Object.keys(EMOJI)) {
    const char = EMOJI[code]!;
    const i = code.indexOf(q);
    if (i === 0) prefix.push({ code, char });
    else if (i > 0) contains.push({ code, char });
    if (prefix.length >= limit) break;
  }
  return [...prefix, ...contains].slice(0, limit);
}
